protobuf/mayastor.proto

Signed-off-by: shubham <shubham.bajpai@mayadata.io>

feat(pool): add pooltype field

---

protobuf/v1/mayastor.proto

add versioned services for bdev and json rpc
Signed-off-by: Akhil Mohan <akhil.mohan@mayadata.io>

feat(proto): add bdev and json rpc v1 service

---

protobuf/v1/common.proto
protobuf/v1/pool.proto

This adds the ability to export a pool.
Signed-off-by: shubham <shubham.bajpai@mayadata.io>

feat(pool): add export rpc

---

protobuf/v1/bdev.proto
protobuf/v1/common.proto
protobuf/v1/pool.proto
protobuf/v1/replica.proto

- add new replica service into v1 grpc API

feat(proto): add v1 proto for mayastor replica

---

protobuf/v1/host.proto

Signed-off-by: Akhil Mohan <akhil.mohan@datacore.com>

feat(grpc): add v1/host service

---

protobuf/v1/nexus.proto

- add rpc methods for nexus child operations and rebuild

feat(proto): add nexus child operations 

---

protobuf/v1/nexus.proto

Add the nexus info key to v1/nexus.proto.

chore(nexus info key): add to v1

---

protobuf/mayastor.proto
protobuf/v1/nexus.proto

This is API extension for Nexus-level fault injection.
See this PR: https://github.com/openebs/mayastor/pull/1166

feat(nexus): nexus-level fault injection api

---

Cargo.toml
build.rs
src/lib.rs
src/v0.rs
src/v1.rs

Signed-off-by: Dmitry Savitskiy <dmitry.savitsky@datacore.com>

chore(rpc): sharing rust rpc definitions

---

build.rs

Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

fix: remove submodule checkout

---

protobuf/v1/nexus.proto
src/v0.rs
src/v1.rs

Signed-off-by: Dmitry Savitskiy <dmitry.savitskiy@datacore.com>

feat(nexus): child state reason added

---

protobuf/v1/replica.proto

Signed-off-by: Abhishek Agarwal <abhishek.agarwal@mayadata.io>

chore: add poolname in replica proto message

---

.pre-commit-config.yaml
shell.nix

Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

fix: add missing cacert for pure environments

---

protobuf/mayastor.proto
protobuf/v1/nexus.proto

Added nexus shutdown gRPC methods for both v0 and v1 API.
Signed-off-by: Mikhail Tcymbaliuk <mtzaurus@gmail.com>

feat(api): nexus shutdown api

---

protobuf/mayastor.proto
protobuf/v1/nexus.proto

Signed-off-by: Dmitry Savitskiy <dmitry.savitskiy@datacore.com>

feat(nexus): child device name in child properties

---

src/v1.rs

expose ShareProtocol for v1 nexus

chore: expose ShareProtocol for v1 nexus

---

Cargo.toml
build.rs
protobuf/mayastor.proto
protobuf/v1/nexus.proto

Added new API for getting nexus rebuild history.

feat: mayastor-api: Rebuild History API

---

protobuf/v1/nexus.proto
protobuf/v1/pool.proto
protobuf/v1/replica.proto
src/v1.rs

Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

fix: add list by uuid

---

protobuf/v1/nexus.proto
protobuf/v1/pool.proto
protobuf/v1/replica.proto
src/v1.rs

fix: add list by uuid
fix: return nexus for shutdown/fault in v1
Signed-off-by: Tiago Castro <tiagolobocastro@gmail.com>

chore: cherry-pick pull request #45 from openebs/list-uuid

---

protobuf/v1/nexus.proto

Added CreateSnapshot method to V1 Nexus gRPC API.

feat(nexus): nexus create snapshot api
